language: cpp
compiler: gcc
before_install:
  - sudo apt-get update -qq
  - sudo add-apt-repository ppa:v-launchpad-jochen-sprickerhof-de/pcl -y
  - sudo apt-get update -qq
  - sudo apt-get install -y libpcl-all
before_script:
  - mkdir build
  - cd build
  - cmake ..
script: make
after_script: sample_icp
